pipeline:
  test:
    image: maven:alpine
    commands:
      - mvn --quiet --batch-mode test
  
  build_jar:
    image: maven:alpine
    commands:
    - mvn --batch-mode clean package

  ecr:
    image: plugins/ecr
    access_key : <AWS_ACCESS_KEY>
    secret_key : <AWS_SECRET_KEY>
    registry: 0000000000.dkr.ecr.ap-southeast-1.amazonaws.com
    repo: 0000000000.dkr.ecr.ap-southeast-1.amazonaws.com/sample-web-app
    tags: latest
    file: Dockerfile
